### ISSUE TITLE
DUO Grid is utilizing 0px breakpoint @media (min-width: 0px)

### ISSUE THREAD

**Issue by vlad-saling** [IBM/grid#12]
DUO Grid is utilising 0px breakpoint @media (min-width: 0px). This forced a mapping of v18 breakpoints with an offset (when DUO is integrated in v18 and it should respond to same width). Is mentioned breakpoint needed? If it's because mobile-first, I believe it can be applied without a breakpoint.

Context: https://github.ibm.com/digital-marketing-tcx-cloud/v18-duo-integration/issues/8

**Comment by seejamescode** [comment]
Hi @vlad-saling! That was the case for the grid, but has since been resolved.

The old grid with this mistake is probably still alive on our internal Github. That repo will be removed when the example pages are migrated here.

**Comment by vlad-saling** [comment]
Thanks
