### ISSUE TITLE
Hiding a column in both small and medium breakpoints does not work.

### ISSUE THREAD

**Issue by TazmanianD** [IBM/grid#16]
The following html does not work correctly:

```
    <div className="ibm-grid">
        <div className="ibm-col-group">
            <div className="ibm-col-sm-3 ibm-col-md-2 ibm-col-lg-7">
                Title
            </div>
            <div className="ibm-col-sm-0-only ibm-col-md-1 ibm-col-lg-1">
                Grade
            </div>
            <div className="ibm-col-sm-0-only ibm-col-md-1 ibm-col-lg-1">
                Pains
            </div>
            <div className="ibm-col-sm-0-only ibm-col-md-1 ibm-col-lg-2">
                Complexity
            </div>
            <div className="ibm-col-sm-0-only ibm-col-md-0-only ibm-col-lg-2">
                Date
            </div>
            <div className="ibm-col-sm-0-only ibm-col-md-2 ibm-col-lg-2">
                Competitor
            </div>
            <div className="ibm-col-sm-1 ibm-col-md-1 ibm-col-lg-1">
                Overflow
            </div>
        </div>
    </div>
```

At the medium breakpoint, the "Date" column is not supposed to be displayed but it is. The small and large breakpoints render as expected. If I remove all the "-sm" classes so we only specify the medium and large columns, then the medium breakpoint does render as expected so somehow the small column definitions are breaking the medium breakpoint.

**Comment by seejamescode** [comment]
Hey @TazmanianD! I think this example does everything you want: https://codepen.io/seejamescode/pen/zPdGQe

Two changes to classes:

1. `ibm`, not `ibm-grid`
2. `ibm-col-sm-0 ibm-col-lg-2` to hide in multiple breakpoints

Let me know if this did not resolve what you are trying to achieve.

**Comment by TazmanianD** [comment]
Yeah, that does appear to work. I don't understand what the difference is between `ibm-col-sm-0` and `ibm-col-sm-0-only`.

**Comment by seejamescode** [comment]
Use `ibm-col-sm-0-only` if you want the element to reappear at the medium breakpoint.

**Comment by TazmanianD** [comment]
@seejamescode I'm afraid I still don't understand. The doc for `.ibm-col-[sm, md, lg]-0-only` says "Do not display a column at a specific breakpoint". That sounds to me like `ibm-col-sm-0-only` would just not show the column at the small breakpoint but doesn't say anything about the medium or large breakpoints. Of course, that's also what I might expect `ibm-col-sm-0` to mean so I don't understand the difference. When should I use the `0-only` style instead of just `0`? What does the "only" part mean?

Also you closed this issue but it seems like it's still a bug. It's great you gave me the workaround but if someone doesn't know about that workaround, I'm not sure they would necessarily be able to figure it out on their own.

Also, I see that using just the `0` styles has the same problem. If I say that both the small and medium breakpoints should not show a column, it seems that the medium column appears anyway: `ibm-col-sm-0 ibm-col-md-0 ibm-col-lg-2`.
