### ISSUE TITLE
Trouble getting the full 'ibm-col-bleed' to work

### ISSUE THREAD

**Issue by rickymor** [IBM/grid#17]
I'm trying to get the full bleed to work using the grid, as shown in the following example, but I'm having no luck (there is too much padding on the bleed element):
<img width="1410" alt="screenshot1" src="https://user-images.githubusercontent.com/33820082/33001281-cb09cc28-cd7a-11e7-8046-2969d981b4a4.png">

That being said, upon closer inspection, I realized that the example HTML and CSS provided in the demo actually makes use of an 'example' class not found in the actual grid file:
<img width="1224" alt="screenshot2" src="https://user-images.githubusercontent.com/33820082/33001279-caf5480c-cd7a-11e7-811c-a62013dd3eab.png">

Is this by design, or is the CSS for the bleed still in the works?

Thanks!

**Comment by seejamescode** [comment]
`.example` for that page is undoing all margin and expanding outside of the page’s grid so we can use a fresh copy.

The full bleed should only work if it is a direct child of `.ibm` or a chain of `.ibm-col-group`. Is this the case for you?

**Comment by rickymor** [comment]
Ah yes, I see my error now. Apologies – thanks for your time! 
----- Original message -----From: James Y Rauhut <notifications@github.com>To: IBM/grid <grid@noreply.github.com>Cc: rickymor <rickymor@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBM/grid] Trouble getting the full 'ibm-col-bleed' to work (#17)Date: Sun, Nov 26, 2017 11:33 PM 
.example for that page is undoing all margin and expanding outside of the page’s grid so we can use a fresh copy.
The full bleed should only work if it is a direct child of .ibm or a chain of .ibm-col-group. Is this the case for you?

**Comment by seejamescode** [comment]
Glad I could help!
