### ISSUE TITLE
inner container bleeding out of the root container

### ISSUE THREAD

**Issue by umeshbalegar** [IBM/grid#8]
DUO Grid bleeding didn't work properly when customizing internal container. Basically the inner container was bleeding out of the root container.

![2c4eef579b1b192](https://user-images.githubusercontent.com/9473037/31238587-668ec26a-a9c8-11e7-8403-0c1053bcfd97.jpg)

**Comment by seejamescode** [comment]
Hey @umeshbalegar, I am having trouble seeing what is off here. Can you tell me what content should be displaying in the red? Screenshots with the grid checker will also help.

Bleed classnames are meant to extend background colors and images. Is something else being attempted?

**Comment by umeshbalegar** [comment]
Hey @seejamescode , the border bottom is applied to the inner div, as you can see the container div which is highlighted in blue, but the inner div which has the border goes beyond the container width

**Comment by seejamescode** [comment]
Ah, I gotcha! This is due to that div having the bleed.

Can you try moving that border classname to the next child inside itself? If that does not work, please paste an html snippet for me.

**Comment by seejamescode** [comment]
Did the explanation in #7 help solve this one?

**Comment by seejamescode** [comment]
Hey @umeshbalegar, please leave me an update by the end of the week. If not, I will assume you got it from our conversation in #7!

**Comment by umeshbalegar** [comment]
Yes I had to move couple of things and it worked out thanks James

**Comment by umeshbalegar** [comment]
Thanks for your help James, looks like the fix for #7 worked well

**Comment by seejamescode** [comment]
Happy we could figure it out together!
